{% set name = "lammps-dp" %}
{% set version = "1.0.1" %}
{% set lammps = "stable_7Aug2019" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lammps/lammps/archive/{{ lammps }}.tar.gz
  sha256: 5380c1689a93d7922e3d65d9c186401d429878bb3cbe9a692580d3470d6a253f
  patches: 
    - deepmd.patch
    
build:
  number: 0
  string: "{{ PKG_BUILDNUM }}_{{ dp_variant }}"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make 
  
  host:
    - libdeepmd {{ version }} *{{ dp_variant }}
    - mpich
    - zlib
    - fftw
    - libpng
    - jpeg

  run:
    - libdeepmd {{ version }} *{{ dp_variant }}
    - {{ pin_compatible('mpich') }}
    - fftw
    - libpng
    - jpeg

test:
  files:
    - input.lammps
    - water.lmp
    - frozen_model.pb
  commands: 
    - lmp -help
    - lmp -in input.lammps

about:
  home: http://lammps.sandia.gov
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'LAMMPS stands for Large-scale Atomic/Molecular Massively Parallel Simulator.'

  description: |
    LAMMPS is a classical molecular dynamics simulation code designed to
    run efficiently on parallel computers.  It was developed at Sandia
    National Laboratories, a US Department of Energy facility, with
    funding from the DOE.  It is an open-source code, distributed freely
    under the terms of the GNU Public License (GPL).
  doc_url: http://lammps.sandia.gov/doc/Manual.html
  dev_url: https://github.com/lammps/lammps

extra:
  recipe-maintainers:
    - njzjz
