tflow_variant:
- gpu
# cuda 9.0, gcc 5.4, cudnn 7.3
# cuda 9.2, gcc 5.4, cudnn 7.3
# cuda 10.0, gcc 5.4, cudnn 7.3
# cuda 10.1, gcc 5.4, cudnn 7.6
c_compiler_version:
- 5.4
cxx_compiler_version:
- 5.4
cudatoolkit:
- 10.1
cudnn:
- 7.6
