CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk
c_compiler: gcc
c_compiler_version: '5.4'
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cudatoolkit: '10.1'
cudnn: '7.6'
cxx_compiler: gxx
cxx_compiler_version: '5.4'
extend_keys:
- extend_keys
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
tflow_variant: gpu
